<?php
/**
 * Created by PhpStorm.
 * User: abdellah
 * Date: 19/07/18
 * Time: 17:01
 */

namespace Test\Controller;

use App\Entity\Comment;
use App\Entity\User;
use Doctrine\Common\Persistence\PersistentObject;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use PHPUnit\Util\Json;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\BrowserKit;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class CommentControllerFunctionalTest extends WebTestCase
{
    protected function setUp()
    {
        //** @var PersistentObject persist,flush */

        static::createClient();

        $em = self::$kernel->getContainer()->get('doctrine.orm.entity_manager');

        $this->createDb($em);

        $loader = new \Nelmio\Alice\Loader\NativeLoader();
        $objectSet = $loader->loadFile(__DIR__ . '/../Fixtures/fixtures.yml')->getObjects();

        foreach ($objectSet as $object) {
            $em->persist($object);
        }

        $em->flush();
        $em->clear();

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testCreateCommentFunctionalAction()
    {

        $em = self::$kernel->getContainer()->get('doctrine.orm.entity_manager');

        $client = self::$kernel->getContainer()->get('test.client');

        $client->request("POST", "/comment", array(), array(),
            array(), '{"id":"cfp5kdff85545","title":"la decouvert du continent ameriquain","description":"par dessus les collines et les riviere","user_id":"32132dsf132ds1f3ds21fsd"}', true);

        $this->assertSame(200, $client->getResponse()->getStatusCode());

        //recupere la response la jsondecode , la transforme en string, puis avec le param true je peux utiliser un tab associaatif
        $contentId = json_decode($client->getResponse()->getContent(), true);

        $comment = $em->getRepository(Comment::class)->find($contentId["id"]);

        $this->assertEquals("la decouvert du continent ameriquain", $comment->getTitle());
        $this->assertEquals("par dessus les collines et les riviere", $comment->getDescription());
        $this->assertEquals("32132dsf132ds1f3ds21fsd", $comment->getUser()->getId());

    }


    public function testModifyCommentAction()
    {
        $em = self::$kernel->getContainer()->get('doctrine.orm.entity_manager');

        $client = self::$kernel->getContainer()->get('test.client');

        $client->request("PUT", "/modify_comment/654984ds65f1d651f6s5d1f", array(), array(), array(), '{"id":"654984ds65f1d651f6s5d1f","title":"roots","description":"les decouvertes africaine dans le temps","user_id":"32132dsf132ds1f3ds21fsd"}', true);

        $this->assertSame(200, $client->getResponse()->getStatusCode());

        $comment = $em->getRepository(Comment::class)->findOneBy(["id" => "654984ds65f1d651f6s5d1f"]);

        $this->assertEquals("roots", $comment->getTitle());
        $this->assertEquals("les decouvertes africaine dans le temps", $comment->getDescription());
        $this->assertEquals("32132dsf132ds1f3ds21fsd", $comment->getUser()->getId());

    }

    public function testDeleteCommentAction()
    {
        $client = self::$kernel->getContainer()->get('test.client');

        $client->request("DELETE", "/delete_comment/654984ds65f1d651f6s5d1f");

        $this->assertSame(200, $client->getResponse()->getStatusCode());

    }


    private function createDb(EntityManager $em)
    {
        $tool = new \Doctrine\ORM\Tools\SchemaTool($em);
        $classes = [];
        /** @var ClassMetadata $class */

        foreach ($em->getMetadataFactory()->getAllMetadata() as $class) {
            $classes[] = $class;
        }

        $tool->dropSchema($classes);
        $tool->createSchema($classes);
    }
}