<?php
/**
 * Created by PhpStorm.
 * User: abdellah
 * Date: 19/07/18
 * Time: 17:01
 */

namespace Test\Controller;

use App\Entity\Comment;
use App\Entity\User;
use Doctrine\Common\Persistence\PersistentObject;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use PHPUnit\Util\Json;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\BrowserKit;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class CommentControllerFunctionalTest extends WebTestCase
{
    protected function setUp()
    {
        /** @var PersistentObject persist,flush */

        static::createClient();

        $em = self::$kernel->getContainer()->get('doctrine.orm.entity_manager');

        $this->createDb($em);

        $loader = new \Nelmio\Alice\Loader\NativeLoader();
        $objectSet = $loader->loadFile(__DIR__ . '/../Fixtures/fixtures.yml')->getObjects();

        foreach ($objectSet as $object) {
            $em->persist($object);
        }

        $em->flush();
        $em->clear();

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testCreateCommentAction()
    {
        /**@var Comment $comment**/
        $em = self::$kernel->getContainer()->get('doctrine.orm.entity_manager');

        $client = self::$kernel->getContainer()->get('test.client');

        $client->request("POST", "/comment", array(), array(), array(), '{"id":"commentaire3","title":"title du com3","description":"description du com3","user_id":"cd"}', true);

        $this->assertSame(200, $client->getResponse()->getStatusCode());

        $comment = $em->getRepository(Comment::class)->find("commentaire3");

        $this->assertEquals("title du com3", $comment->getTitle());
        $this->assertEquals("description du com3", $comment->getDescription());
        $this->assertEquals("cd", $comment->getUser()->getId());

    }


    public function testModifyCommentAction()

    {
        /**@var Comment $comment * */
       /**@var User $user * */

        $em = self::$kernel->getContainer()->get('doctrine.orm.entity_manager');

        $client = self::$kernel->getContainer()->get('test.client');

        $client->request("PUT", "/modify_comment/commentaire1", array(), array(), array(), '{"id":"commentaire1","title":"mon new title","description":"ma new description","user_id":"cd"}', true);

        $this->assertSame(200, $client->getResponse()->getStatusCode());

        $comment = $em->getRepository(Comment::class)->findOneBy(["id" => "commentaire1"]);

        $this->assertEquals("mon new title", $comment->getTitle());
        $this->assertEquals("ma new description", $comment->getDescription());
        $this->assertEquals("cd", $comment->getUser()->getId());

    }

    public function testDeleteCommentAction()
    {
        $client = self::$kernel->getContainer()->get('test.client');

        $client->request("DELETE", "/delete_comment/commentaire1");

        $this->assertSame(200, $client->getResponse()->getStatusCode());

    }


    private function createDb(EntityManager $em)
    {
        $tool = new \Doctrine\ORM\Tools\SchemaTool($em);
        $classes = [];
        /** @var ClassMetadata $class */

        foreach ($em->getMetadataFactory()->getAllMetadata() as $class) {
            $classes[] = $class;
        }

        $tool->dropSchema($classes);
        $tool->createSchema($classes);
    }
}